"""Active Directory tools — enumeration, attack paths, credential attacks (6 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

ACTIVE_DIRECTORY_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="bloodhound",
        title="BloodHound (AD Attack Paths)",
        description="Uses graph theory to reveal hidden attack paths in Active Directory/Azure environments.",
        category="Active Directory",
        install_commands=[
            "pip install --user bloodhound",
            "sudo apt-get install -y neo4j",
        ],
        run_command="bloodhound-python -d {target} -ns {target}",
        project_url="https://github.com/BloodHoundAD/BloodHound",
        tags=["ad", "attack-path", "graph", "enum", "azure"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux", "macos"],
    ),
    HackingToolDef(
        name="netexec",
        title="NetExec — nxc (Network Pentesting)",
        description="Swiss army knife for pentesting Windows/AD networks. Successor to CrackMapExec.",
        category="Active Directory",
        install_commands=["pip install --user netexec"],
        run_command="nxc smb {target}",
        project_url="https://github.com/Pennyw0rth/NetExec",
        tags=["ad", "network", "smb", "windows", "post-exploit"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux", "macos"],
    ),
    HackingToolDef(
        name="impacket",
        title="Impacket (Network Protocol Tools)",
        description="Python classes for working with SMB, MSRPC, Kerberos, LDAP, and more.",
        category="Active Directory",
        install_commands=["pip install --user impacket"],
        run_command="impacket-smbclient {target}",
        project_url="https://github.com/fortra/impacket",
        tags=["ad", "smb", "kerberos", "ldap", "protocol"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux", "macos"],
    ),
    HackingToolDef(
        name="responder",
        title="Responder (LLMNR/NBT-NS Poisoner)",
        description="LLMNR/NBT-NS/MDNS poisoner with rogue authentication servers for credential capture.",
        category="Active Directory",
        install_commands=["git clone https://github.com/lgandx/Responder.git"],
        run_command="cd Responder && sudo python3 Responder.py -I {target}",
        project_url="https://github.com/lgandx/Responder",
        tags=["ad", "poisoner", "credential-capture", "llmnr", "nbns"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="certipy",
        title="Certipy (AD Certificate Abuse)",
        description="Active Directory Certificate Services enumeration and abuse tool.",
        category="Active Directory",
        install_commands=["pip install --user certipy-ad"],
        run_command="certipy find -u {target}",
        project_url="https://github.com/ly4k/Certipy",
        tags=["ad", "certificate", "adcs", "enum", "abuse"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux", "macos"],
    ),
    HackingToolDef(
        name="kerbrute",
        title="Kerbrute (Kerberos Brute Force)",
        description="Kerberos pre-auth brute-forcer for username enumeration and password spraying.",
        category="Active Directory",
        install_commands=["go install github.com/ropnop/kerbrute@latest"],
        run_command="kerbrute userenum -d {target}",
        project_url="https://github.com/ropnop/kerbrute",
        tags=["ad", "kerberos", "bruteforce", "enum", "spray"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux", "macos"],
    ),
]
