"""Forensics tools — memory, disk, network, file analysis (9 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

FORENSICS_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="autopsy",
        title="Autopsy (Digital Forensics Platform)",
        description="Platform for cyber investigation — recover deleted files, extract image metadata.",
        category="Forensics",
        install_commands=["sudo apt-get install -y autopsy"],
        run_command="sudo autopsy",
        tags=["forensics", "disk", "recovery", "metadata"],
        safety_tier=SafetyTier.SAFE,
        requires_root=True,
    ),
    HackingToolDef(
        name="wireshark",
        title="Wireshark (Network Analyzer)",
        description="Network capture and analyzer to see what's happening in your network.",
        category="Forensics",
        install_commands=["sudo apt-get install -y wireshark"],
        run_command="sudo wireshark",
        tags=["forensics", "network", "capture", "analyzer"],
        safety_tier=SafetyTier.SAFE,
        requires_root=True,
    ),
    HackingToolDef(
        name="bulk-extractor",
        title="Bulk Extractor",
        description="Extract useful information without parsing the file system — email, URLs, credit cards.",
        category="Forensics",
        install_commands=["sudo apt-get install -y bulk-extractor"],
        run_command="bulk_extractor {target}",
        project_url="https://github.com/simsong/bulk_extractor",
        tags=["forensics", "extraction", "disk", "email", "url"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="guymager",
        title="Guymager (Disk Clone & ISO Acquire)",
        description="Free forensic imager for media acquisition.",
        category="Forensics",
        install_commands=["sudo apt install guymager"],
        run_command="sudo guymager",
        project_url="https://guymager.sourceforge.io/",
        tags=["forensics", "disk", "clone", "imaging"],
        safety_tier=SafetyTier.SAFE,
        requires_root=True,
    ),
    HackingToolDef(
        name="toolsley",
        title="Toolsley (Web Forensics Tools)",
        description="Web-based forensics toolbox: file signature verifier, hash & validate, binary inspector, encode text, data URI generator, password generator.",
        category="Forensics",
        install_commands=["sudo apt-get install -y python3"],
        run_command="python3 -c \"import hashlib, sys; print(hashlib.sha256(sys.argv[1].encode()).hexdigest())\" {target}",
        project_url="https://www.toolsley.com/",
        tags=["forensics", "web", "hash", "encode", "binary"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux", "macos", "windows"],
    ),
    HackingToolDef(
        name="volatility3",
        title="Volatility 3 (Memory Forensics)",
        description="The world's most widely used memory forensics framework. Usage: python3 vol.py -f memory.dmp windows.pslist",
        category="Forensics",
        install_commands=[
            "git clone https://github.com/volatilityfoundation/volatility3.git",
            "cd volatility3 && pip install --user -r requirements.txt",
        ],
        run_command="cd volatility3 && python3 vol.py -f {target}",
        project_url="https://github.com/volatilityfoundation/volatility3",
        tags=["forensics", "memory", "analysis", "malware"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="binwalk",
        title="Binwalk (Firmware Analysis)",
        description="Analyze, reverse engineer, and extract firmware images. Usage: binwalk firmware.bin",
        category="Forensics",
        install_commands=["pip install --user binwalk"],
        run_command="binwalk {target}",
        project_url="https://github.com/ReFirmLabs/binwalk",
        tags=["forensics", "firmware", "extraction", "reverse"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux", "macos"],
    ),
    HackingToolDef(
        name="pspy",
        title="pspy (Process Monitor — No Root)",
        description="Monitor Linux processes without root — detects cron jobs, scheduled tasks, other users' commands.",
        category="Forensics",
        install_commands=[
            "curl -sSL https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64 -o pspy",
            "chmod +x pspy",
        ],
        run_command="./pspy",
        project_url="https://github.com/DominicBreuker/pspy",
        tags=["forensics", "process", "monitor", "linux", "privesc"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
    ),
]
