"""Information Gathering tools — recon, OSINT, scanning (27 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

INFORMATION_GATHERING_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="nmap",
        title="Network Map (nmap)",
        description="Free and open source utility for network discovery and security auditing.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/nmap/nmap.git",
            "sudo chmod -R 755 nmap && cd nmap && sudo ./configure && make && sudo make install",
        ],
        run_command="nmap {target}",
        project_url="https://github.com/nmap/nmap",
        tags=["recon", "network", "scanner", "port-scan"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="dracnmap",
        title="Dracnmap",
        description="Exploit network and gather information with nmap help via a GUI wrapper.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/Screetsec/Dracnmap.git",
            "cd Dracnmap && chmod +x dracnmap-v2.2-dracOs.sh dracnmap-v2.2.sh",
        ],
        run_command="cd Dracnmap && sudo ./dracnmap-v2.2.sh",
        project_url="https://github.com/Screetsec/Dracnmap",
        tags=["recon", "nmap", "network"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="portscan",
        title="Port Scanning (built-in)",
        description="Built-in port scanner using nmap -O -Pn against a target IP.",
        category="Information Gathering",
        run_command="sudo nmap -O -Pn {target}",
        tags=["recon", "port-scan", "network"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="host2ip",
        title="Host to IP",
        description="Resolve a hostname to its IP address using DNS lookup.",
        category="Information Gathering",
        run_command="python3 -c \"import socket; print(socket.gethostbyname('{target}'))\"",
        tags=["recon", "dns", "network"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux", "macos", "windows"],
    ),
    HackingToolDef(
        name="xerosploit",
        title="Xerosploit",
        description="Penetration testing toolkit for man-in-the-middle attacks.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/LionSec/xerosploit.git",
            "cd xerosploit && sudo python install.py",
        ],
        run_command="sudo xerosploit",
        project_url="https://github.com/LionSec/xerosploit",
        tags=["mitm", "network"],
        safety_tier=SafetyTier.CAUTION,
        requires_root=True,
    ),
    HackingToolDef(
        name="redhawk",
        title="RED HAWK (All In One Scanning)",
        description="All in one tool for Information Gathering and Vulnerability Scanning.",
        category="Information Gathering",
        install_commands=["git clone https://github.com/Tuhinshubhra/RED_HAWK.git"],
        run_command="cd RED_HAWK && php rhawk.php",
        project_url="https://github.com/Tuhinshubhra/RED_HAWK",
        tags=["recon", "scanner", "vuln"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="reconspider",
        title="ReconSpider (OSINT Framework)",
        description="Advanced OSINT framework for scanning IP addresses, emails, websites, and organizations.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/bhavsec/reconspider.git",
            "sudo apt install -y python3 python3-pip && cd reconspider && pip install --user .",
        ],
        run_command="cd reconspider && python3 reconspider.py",
        project_url="https://github.com/bhavsec/reconspider",
        tags=["osint", "recon", "scanner"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="isitdown",
        title="IsItDown (Check Website Down/Up)",
        description="Check whether a website is online or not via isitdownrightnow.com.",
        category="Information Gathering",
        tags=["web", "check", "monitor"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux", "macos", "windows"],
    ),
    HackingToolDef(
        name="infoga",
        title="Infoga - Email OSINT",
        description="Gather email account information (IP, hostname, country) from public sources.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/m4ll0k/Infoga.git",
            "cd Infoga && pip install --user .",
        ],
        run_command="cd Infoga && python3 infoga.py",
        project_url="https://github.com/m4ll0k/Infoga",
        tags=["osint", "email", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="recondog",
        title="ReconDog",
        description="ReconDog Information Gathering Suite for multi-source recon.",
        category="Information Gathering",
        install_commands=["git clone https://github.com/s0md3v/ReconDog.git"],
        run_command="cd ReconDog && sudo python dog",
        project_url="https://github.com/s0md3v/ReconDog",
        tags=["osint", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="striker",
        title="Striker",
        description="Recon & Vulnerability Scanning Suite.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/s0md3v/Striker.git",
            "cd Striker && pip3 install -r requirements.txt",
        ],
        run_command="cd Striker && sudo python3 striker.py {target}",
        project_url="https://github.com/s0md3v/Striker",
        tags=["recon", "scanner", "vuln"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="secretfinder",
        title="SecretFinder (API Keys & Secrets)",
        description="Find sensitive data like API keys, access tokens, JWTs in JavaScript files.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/m4ll0k/SecretFinder.git secretfinder",
            "cd secretfinder && sudo pip3 install -r requirements.txt",
        ],
        run_command="cd secretfinder && python3 SecretFinder.py -h",
        project_url="https://github.com/m4ll0k/SecretFinder",
        tags=["osint", "secrets", "web", "api"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="shodanfy",
        title="Find Info Using Shodan",
        description="Get ports, vulnerabilities, and info for any IP via Shodan (no API key, no rate limit).",
        category="Information Gathering",
        install_commands=["git clone https://github.com/m4ll0k/Shodanfy.py.git"],
        run_command="cd Shodanfy.py && python3 shodanfy.py {target}",
        project_url="https://github.com/m4ll0k/Shodanfy.py",
        tags=["osint", "shodan", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="rang3r",
        title="Port Scanner - rang3r",
        description="Multi-threaded Python script that scans all alive hosts within a specified IP range.",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/floriankunushevci/rang3r.git",
            "pip install --user termcolor",
        ],
        run_command="cd rang3r && sudo python3 rang3r.py --ip {target}",
        project_url="https://github.com/floriankunushevci/rang3r",
        tags=["recon", "port-scan", "network"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="breacher",
        title="Breacher (Admin Panel Finder)",
        description="Advanced multithreaded admin panel finder written in Python.",
        category="Information Gathering",
        install_commands=["git clone https://github.com/s0md3v/Breacher.git"],
        run_command="cd Breacher && python3 breacher.py -u {target}",
        project_url="https://github.com/s0md3v/Breacher",
        tags=["web", "discovery", "admin-panel"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="theHarvester",
        title="theHarvester (OSINT)",
        description="Gather emails, names, subdomains, IPs and URLs from public sources. Usage: theHarvester -d example.com -b all",
        category="Information Gathering",
        install_commands=[
            "git clone https://github.com/laramies/theHarvester.git",
            "cd theHarvester && pip install --user -r requirements/base.txt",
        ],
        run_command="cd theHarvester && python3 theHarvester.py -d {target} -b all",
        project_url="https://github.com/laramies/theHarvester",
        tags=["osint", "email", "subdomain", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="amass",
        title="Amass (Attack Surface Mapping)",
        description="In-depth subdomain enumeration and attack surface mapping. Usage: amass enum -d example.com",
        category="Information Gathering",
        install_commands=["go install -v github.com/owasp-amass/amass/v4/...@master"],
        run_command="amass enum -d {target}",
        project_url="https://github.com/owasp-amass/amass",
        tags=["osint", "subdomain", "dns", "recon", "enum"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="masscan",
        title="Masscan (Fast Port Scanner)",
        description="Fastest internet port scanner — 10 million packets/sec. Usage: masscan -p1-65535 <IP> --rate=1000",
        category="Information Gathering",
        install_commands=["sudo apt-get install -y masscan"],
        run_command="masscan {target}",
        project_url="https://github.com/robertdavidgraham/masscan",
        tags=["recon", "port-scan", "network", "fast"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="rustscan",
        title="RustScan (Modern Port Scanner)",
        description="Scans all 65k ports in 3 seconds, passes results to nmap automatically. Usage: rustscan -a <IP> -- -sV",
        category="Information Gathering",
        install_commands=[
            "curl -sLO https://github.com/RustScan/RustScan/releases/latest/download/rustscan_2.3.0_amd64.deb",
            "sudo dpkg -i rustscan_2.3.0_amd64.deb",
        ],
        run_command="rustscan -a {target}",
        project_url="https://github.com/RustScan/RustScan",
        tags=["recon", "port-scan", "network", "fast"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="holehe",
        title="Holehe (Email → Social Accounts)",
        description="Check if an email address is registered on 120+ websites. Usage: holehe user@example.com",
        category="Information Gathering",
        install_commands=["pip install --user holehe"],
        run_command="holehe {target}",
        project_url="https://github.com/megadose/holehe",
        tags=["osint", "email", "social"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="maigret",
        title="Maigret (Username OSINT)",
        description="Collect a dossier on a person by username across 3000+ sites. Usage: maigret <username>",
        category="Information Gathering",
        install_commands=["pip install --user maigret"],
        run_command="maigret {target}",
        project_url="https://github.com/soxoj/maigret",
        tags=["osint", "username", "social", "dossier"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="httpx",
        title="httpx (HTTP Toolkit)",
        description="Fast multi-purpose HTTP probing tool. Usage: httpx -l urls.txt -status-code -title -tech-detect",
        category="Information Gathering",
        install_commands=["go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest"],
        run_command="httpx -u {target}",
        project_url="https://github.com/projectdiscovery/httpx",
        tags=["recon", "web", "http", "probing"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="spiderfoot",
        title="SpiderFoot (OSINT Automation)",
        description="Automates OSINT collection for threat intelligence and attack surface mapping.",
        category="Information Gathering",
        install_commands=["pip install --user spiderfoot"],
        run_command="spiderfoot -s {target}",
        project_url="https://github.com/smicallef/spiderfoot",
        tags=["osint", "recon", "automation", "threat-intel"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="subfinder",
        title="Subfinder (Subdomain Enumeration)",
        description="Fast passive subdomain enumeration using multiple sources.",
        category="Information Gathering",
        install_commands=["go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"],
        run_command="subfinder -d {target}",
        project_url="https://github.com/projectdiscovery/subfinder",
        tags=["osint", "subdomain", "dns", "enum", "passive"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="trufflehog",
        title="TruffleHog (Secret Scanner)",
        description="Find, verify, and analyze leaked credentials across git repos, S3 buckets, filesystems.",
        category="Information Gathering",
        install_commands=["pip install --user trufflehog"],
        run_command="trufflehog filesystem {target}",
        project_url="https://github.com/trufflesecurity/trufflehog",
        tags=["secrets", "git", "credentials", "scan"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="gitleaks",
        title="Gitleaks (Git Secret Scanner)",
        description="Fast secret scanner for git repos — detects hardcoded passwords, API keys, tokens.",
        category="Information Gathering",
        install_commands=["go install github.com/gitleaks/gitleaks/v8@latest"],
        run_command="gitleaks detect --source {target}",
        project_url="https://github.com/gitleaks/gitleaks",
        tags=["secrets", "git", "credentials", "scan"],
        safety_tier=SafetyTier.SAFE,
    ),
]
