"""Other Tools — misc sub-categories: Android, Email, Hash, Homograph, Social, WiFi Jam, Payload Inject, Crawling, Mix (23 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

OTHER_TOOLS: list[HackingToolDef] = [
    # === Android Hacking ===
    HackingToolDef(
        name="keydroid",
        title="Keydroid (Android Keylogger)",
        description="Android Keylogger + Reverse Shell.",
        category="Other Tools",
        install_commands=["git clone https://github.com/F4dl0/keydroid.git"],
        run_command="cd keydroid && bash keydroid.sh",
        project_url="https://github.com/F4dl0/keydroid",
        tags=["android", "keylogger", "malware", "reverse-shell"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="mysms",
        title="MySMS (SMS Hijack)",
        description="Script that generates an Android App to hack SMS through WAN.",
        category="Other Tools",
        install_commands=["git clone https://github.com/papusingh2sms/mysms.git"],
        run_command="cd mysms && bash mysms.sh",
        project_url="https://github.com/papusingh2sms/mysms",
        tags=["android", "sms", "malware"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="lockphish",
        title="Lockphish (Lock Screen Phishing)",
        description="Phishing tool for lock screens — grab Windows credentials, Android PIN, and iPhone Passcode.",
        category="Other Tools",
        install_commands=["git clone https://github.com/JasonJerry/lockphish.git"],
        run_command="cd lockphish && bash lockphish.sh",
        project_url="https://github.com/JasonJerry/lockphish",
        tags=["android", "phishing", "windows", "ios", "lock-screen"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="droidcam",
        title="DroidCam / WishFish (Front Camera Capture)",
        description="Powerful tool for grabbing front camera snap using a link.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/kinghacker0/WishFish.git",
            "sudo apt install -y php wget openssh-client",
        ],
        run_command="cd WishFish && sudo bash wishfish.sh",
        project_url="https://github.com/kinghacker0/WishFish",
        tags=["android", "camera", "capture", "phishing"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="evilapp",
        title="EvilApp (Session Hijack)",
        description="Script to generate Android App that can hijack authenticated sessions in cookies.",
        category="Other Tools",
        install_commands=["git clone https://github.com/crypticterminal/EvilApp.git"],
        run_command="cd EvilApp && bash evilapp.sh",
        project_url="https://github.com/crypticterminal/EvilApp",
        tags=["android", "session-hijack", "cookie", "malware"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
    ),

    # === Email Verify ===
    HackingToolDef(
        name="knockmail",
        title="Knockmail (Email Verifier)",
        description="Verify if an email address actually exists.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/heywoodlh/KnockMail.git",
            "cd KnockMail && sudo pip3 install -r requirements.txt",
        ],
        run_command="cd KnockMail && python3 knockmail.py",
        project_url="https://github.com/heywoodlh/KnockMail",
        tags=["email", "verify", "recon", "osint"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === Hash Cracking ===
    HackingToolDef(
        name="hashbuster",
        title="Hash Buster (Cracker)",
        description="Automatic hash type identification and cracking. Supports MD5, SHA1, SHA256, SHA384, SHA512.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/s0md3v/Hash-Buster.git",
            "cd Hash-Buster && make install",
        ],
        run_command="buster -t {target}",
        project_url="https://github.com/s0md3v/Hash-Buster",
        tags=["hash", "cracker", "md5", "sha", "password"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === IDN Homograph Attack ===
    HackingToolDef(
        name="evilurl",
        title="EvilURL (IDN Homograph Generator)",
        description="Generate unicode evil domains for IDN Homograph Attacks and detect them.",
        category="Other Tools",
        install_commands=["git clone https://github.com/UndeadSec/EvilURL.git"],
        run_command="cd EvilURL && python3 evilurl.py",
        project_url="https://github.com/UndeadSec/EvilURL",
        tags=["homograph", "idn", "url", "phishing", "unicode"],
        safety_tier=SafetyTier.CAUTION,
    ),

    # === Social Media Bruteforce ===
    HackingToolDef(
        name="allinone-socialmedia",
        title="AllinOne SocialMedia Attack",
        description="Brute force attack tool for Gmail, Hotmail, Twitter, Facebook, Netflix. Usage: python3 Brute_Force.py -g <Account> -l <File_list>",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/Matrix07ksa/Brute_Force.git",
            "cd Brute_Force && sudo pip3 install proxylist && pip3 install mechanize",
        ],
        run_command="cd Brute_Force && python3 Brute_Force.py -h",
        project_url="https://github.com/Matrix07ksa/Brute_Force",
        tags=["bruteforce", "social-media", "facebook", "gmail", "twitter"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="faceshell",
        title="Facebook Attack (BruteForce)",
        description="Facebook brute-forcer using dictionary attacks.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/Matrix07ksa/Brute_Force.git",
            "cd Brute_Force && sudo pip3 install proxylist && pip3 install mechanize",
        ],
        run_command="cd Brute_Force && python3 Brute_Force.py -f {target} -l wordlist.txt",
        project_url="https://github.com/Matrix07ksa/Brute_Force",
        tags=["bruteforce", "facebook", "social-media"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="appcheck",
        title="Application Checker",
        description="Check if an app is installed on the target device through a link.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/jakuta-tech/underhanded.git",
            "cd underhanded && sudo chmod +x underhanded.sh",
        ],
        run_command="cd underhanded && sudo bash underhanded.sh",
        project_url="https://github.com/jakuta-tech/underhanded",
        tags=["recon", "app", "check", "link"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === Social Media Finder ===
    HackingToolDef(
        name="socialmapper",
        title="Social Mapper (Facial Recognition OSINT)",
        description="Correlates social media profiles via facial recognition across different sites.",
        category="Other Tools",
        install_commands=[
            "sudo apt install -y software-properties-common build-essential cmake libgtk-3-dev libboost-all-dev",
            "git clone https://github.com/Greenwolf/social_mapper.git",
            "cd social_mapper/setup && sudo python3 -m pip install --no-cache-dir -r requirements.txt",
        ],
        run_command="cd social_mapper/setup && python3 social_mapper.py -h",
        project_url="https://github.com/Greenwolf/social_mapper",
        tags=["osint", "facial-recognition", "social-media", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="finduser",
        title="FindUser (Username OSINT)",
        description="Find usernames across over 75 social networks.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/xHak9x/finduser.git",
            "cd finduser && sudo chmod +x finduser.sh",
        ],
        run_command="cd finduser && sudo bash finduser.sh",
        project_url="https://github.com/xHak9x/finduser",
        tags=["osint", "username", "social-media", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="sherlock",
        title="Sherlock (Username OSINT)",
        description="Hunt down social media accounts by username across hundreds of social networks.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/sherlock-project/sherlock.git",
            "cd sherlock && sudo python3 -m pip install -r requirements.txt",
        ],
        run_command="cd sherlock && python3 sherlock {target}",
        project_url="https://github.com/sherlock-project/sherlock",
        tags=["osint", "username", "social-media", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="socialscan",
        title="SocialScan (Email & Username Check)",
        description="Check email address and username availability on online platforms with 100% accuracy.",
        category="Other Tools",
        install_commands=["pip install --user socialscan"],
        run_command="sudo socialscan {target}",
        project_url="https://github.com/iojw/socialscan",
        tags=["osint", "email", "username", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === WiFi Jamming / Deauthentication ===
    HackingToolDef(
        name="wifijammer-ng",
        title="WifiJammer-NG",
        description="Continuously jam all WiFi clients and access points within range.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/MisterBianco/wifijammer-ng.git",
            "cd wifijammer-ng && pip install --user -r requirements.txt",
        ],
        run_command="cd wifijammer-ng && sudo python3 wifijammer.py --help",
        project_url="https://github.com/MisterBianco/wifijammer-ng",
        tags=["wireless", "wifi", "jammer", "deauth"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="kawaiideauther",
        title="KawaiiDeauther",
        description="Pentest toolkit to perform WiFi client/router jamming and spam many fake APs for testing.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/aryanrtm/KawaiiDeauther.git",
            "cd KawaiiDeauther && sudo bash install.sh",
        ],
        run_command="cd KawaiiDeauther && sudo bash KawaiiDeauther.sh",
        project_url="https://github.com/aryanrtm/KawaiiDeauther",
        tags=["wireless", "wifi", "jammer", "deauth", "fake-ap"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),

    # === Payload Injection ===
    HackingToolDef(
        name="debinject",
        title="Debinject (Deb Package Injector)",
        description="Inject malicious code into .deb Debian packages.",
        category="Other Tools",
        install_commands=["git clone https://github.com/UndeadSec/Debinject.git"],
        run_command="cd Debinject && python debinject.py",
        project_url="https://github.com/UndeadSec/Debinject",
        tags=["payload", "injection", "deb", "package"],
        safety_tier=SafetyTier.DANGEROUS,
    ),
    HackingToolDef(
        name="pixload",
        title="Pixload (Image Payload Creator)",
        description="Set of tools for creating and injecting payloads into images.",
        category="Other Tools",
        install_commands=[
            "sudo apt install libgd-perl libimage-exiftool-perl libstring-crc32-perl",
            "git clone https://github.com/chinarulezzz/pixload.git",
        ],
        run_command="cd pixload && ls",
        project_url="https://github.com/chinarulezzz/pixload",
        tags=["payload", "image", "injection", "stegano"],
        safety_tier=SafetyTier.DANGEROUS,
    ),

    # === Web Crawling ===
    HackingToolDef(
        name="gospider",
        title="Gospider (Fast Web Spider)",
        description="Fast web spider written in Go for crawling and discovering endpoints.",
        category="Other Tools",
        install_commands=["go install github.com/jaeles-project/gospider@latest"],
        run_command="gospider -s {target}",
        project_url="https://github.com/jaeles-project/gospider",
        tags=["web", "crawler", "spider", "go", "discovery"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === CloudFlare Bypass ===
    HackingToolDef(
        name="hatcloud",
        title="HatCloud (CloudFlare IP Bypass)",
        description="Bypass CloudFlare to discover real IP address. Built in Ruby.",
        category="Other Tools",
        install_commands=["git clone https://github.com/HatBashBR/HatCloud.git"],
        run_command="cd HatCloud && sudo ruby hatcloud.rb -b {target}",
        project_url="https://github.com/HatBashBR/HatCloud",
        tags=["web", "cloudflare", "bypass", "recon", "ip"],
        safety_tier=SafetyTier.SAFE,
    ),

    # === Mix Tools ===
    HackingToolDef(
        name="terminal-multiplexer",
        title="Terminal Multiplexer (Tilix)",
        description="Tilix — a tiling terminal emulator that allows opening several terminal sessions inside one window.",
        category="Other Tools",
        install_commands=["sudo apt-get install -y tilix"],
        tags=["utility", "terminal", "multiplexer", "tiling"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="crivo",
        title="Crivo (URL/IP Extractor)",
        description="Tool for extracting and filtering URLs, IPs, domains, and subdomains from web pages or text with built-in scraping.",
        category="Other Tools",
        install_commands=[
            "git clone https://github.com/GMDSantana/crivo.git",
            "cd crivo && pip install --user -r requirements.txt",
        ],
        run_command="cd crivo && python3 crivo_cli.py -h",
        project_url="https://github.com/GMDSantana/crivo",
        tags=["web", "extractor", "url", "ip", "scraper"],
        safety_tier=SafetyTier.SAFE,
    ),
]
