"""Payload Creation tools — backdoors, payloads, droppers (8 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

PAYLOAD_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="thefatrat",
        title="The FatRat (Backdoor Generator)",
        description="Easy way to create backdoors and payloads which can bypass most anti-virus.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/Screetsec/TheFatRat.git",
            "cd TheFatRat && chmod +x setup.sh",
        ],
        run_command="cd TheFatRat && sudo bash setup.sh",
        project_url="https://github.com/Screetsec/TheFatRat",
        tags=["payload", "backdoor", "antivirus-bypass", "generator"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="brutal",
        title="Brutal (Payload Toolkit)",
        description="Toolkit to create various payloads, powershell attacks, virus attacks for Human Interface Devices.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/Screetsec/Brutal.git",
            "cd Brutal && chmod +x Brutal.sh",
        ],
        run_command="cd Brutal && sudo bash Brutal.sh",
        project_url="https://github.com/Screetsec/Brutal",
        tags=["payload", "powershell", "hid", "generator"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="stitch",
        title="Stitch (Cross-Platform RAT)",
        description="Cross Platform Python Remote Administrator Tool.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/nathanlopez/Stitch.git",
            "cd Stitch && pip install --user -r lnx_requirements.txt",
        ],
        run_command="cd Stitch && sudo python3 main.py",
        project_url="https://nathanlopez.github.io/Stitch",
        tags=["payload", "rat", "cross-platform", "remote"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="msfvenom",
        title="MSFvenom Payload Creator (MSFPC)",
        description="Wrapper to generate multiple types of Metasploit payloads based on user choice.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/g0tmi1k/msfpc.git",
            "cd msfpc && chmod +x msfpc.sh",
        ],
        run_command="cd msfpc && sudo bash msfpc.sh -h -v",
        project_url="https://github.com/g0tmi1k/msfpc",
        tags=["payload", "metasploit", "generator", "msfvenom"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="venom",
        title="Venom Shellcode Generator",
        description="Exploits apache2 webserver to deliver LAN payloads via fake webpages.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/r00t-3xp10it/venom.git",
            "sudo chmod -R 775 venom*/ && cd venom*/ && cd aux && sudo bash setup.sh",
        ],
        run_command="cd venom && sudo ./venom.sh",
        project_url="https://github.com/r00t-3xp10it/venom",
        tags=["payload", "shellcode", "apache", "lan"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="spycam",
        title="Spycam (Webcam Payload)",
        description="Generates a Win32 payload that captures webcam images every 1 minute.",
        category="Payload Creation",
        install_commands=[
            "git clone https://github.com/indexnotfound404/spycam.git",
            "cd spycam && bash install.sh && chmod +x spycam",
        ],
        run_command="cd spycam && ./spycam",
        project_url="https://github.com/indexnotfound404/spycam",
        tags=["payload", "webcam", "win32", "malicious"],
        safety_tier=SafetyTier.DANGEROUS,
    ),
    HackingToolDef(
        name="mobdroid",
        title="Mob-Droid (Android Payload Generator)",
        description="Generates Metasploit payloads for Android easily without typing long commands.",
        category="Payload Creation",
        install_commands=["git clone https://github.com/kinghacker0/mob-droid.git"],
        run_command="cd mob-droid && sudo python3 mob-droid.py",
        project_url="https://github.com/kinghacker0/Mob-Droid",
        tags=["payload", "android", "metasploit", "generator"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="enigma",
        title="Enigma (Multiplatform Dropper)",
        description="Multiplatform payload dropper for various target systems.",
        category="Payload Creation",
        install_commands=["git clone https://github.com/UndeadSec/Enigma.git"],
        run_command="cd Enigma && sudo python3 enigma.py",
        project_url="https://github.com/UndeadSec/Enigma",
        tags=["payload", "dropper", "multiplatform"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
]
