"""Phishing Attack tools — social engineering and credential harvesting (17 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

PHISHING_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="autophisher",
        title="Autophisher RK",
        description="Automated Phishing Toolkit for security testing.",
        category="Phishing Attack",
        install_commands=["git clone https://github.com/CodingRanjith/autophisher.git"],
        run_command="cd autophisher && sudo bash autophisher.sh",
        project_url="https://github.com/CodingRanjith/autophisher",
        tags=["phishing", "social-engineering", "automation"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="pyphisher",
        title="Pyphisher",
        description="Easy to use phishing tool with 77 website templates.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/KasRoudra/PyPhisher",
            "pip3 install --user -r PyPhisher/files/requirements.txt",
        ],
        run_command="cd PyPhisher && sudo python3 pyphisher.py",
        project_url="https://github.com/KasRoudra/PyPhisher",
        tags=["phishing", "social-engineering", "templates"],
        safety_tier=SafetyTier.DANGEROUS,
        requires_root=True,
    ),
    HackingToolDef(
        name="advphishing",
        title="AdvPhishing (OTP Phishing)",
        description="Advanced Phishing Tool with OTP phishing capabilities.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/Ignitetch/AdvPhishing.git",
            "cd AdvPhishing && chmod +x Linux-Setup.sh && bash Linux-Setup.sh",
        ],
        run_command="cd AdvPhishing && sudo bash AdvPhishing.sh",
        project_url="https://github.com/Ignitetch/AdvPhishing",
        tags=["phishing", "otp", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="setoolkit",
        title="Setoolkit (Social Engineer Toolkit)",
        description="Open-source penetration testing framework designed for social engineering.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/trustedsec/social-engineer-toolkit/",
            "cd social-engineer-toolkit && pip install --user .",
        ],
        run_command="sudo setoolkit",
        project_url="https://github.com/trustedsec/social-engineer-toolkit",
        tags=["phishing", "social-engineering", "framework", "pentest"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="socialfish",
        title="SocialFish",
        description="Automated Phishing Tool & Information Collector.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/UndeadSec/SocialFish.git && sudo apt-get install python3 python3-pip python3-dev -y",
            "cd SocialFish && sudo python3 -m pip install -r requirements.txt",
        ],
        run_command="cd SocialFish && sudo python3 SocialFish.py",
        project_url="https://github.com/UndeadSec/SocialFish",
        tags=["phishing", "social-engineering", "information-gathering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="hiddeneye",
        title="HiddenEye (Modern Phishing)",
        description="Modern Phishing Tool with advanced functionality and multiple tunnelling services.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/Morsmalleo/HiddenEye.git && chmod -R 755 HiddenEye",
            "cd HiddenEye && sudo pip3 install -r requirements.txt && pip3 install pyngrok",
        ],
        run_command="cd HiddenEye && sudo python3 HiddenEye.py",
        project_url="https://github.com/Morsmalleo/HiddenEye",
        tags=["phishing", "ngrok", "tunnelling", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="evilginx3",
        title="Evilginx3 (2FA Bypass Phishing)",
        description="MITM attack framework for phishing login credentials with session cookies, bypassing 2FA. Requires Go.",
        category="Phishing Attack",
        install_commands=[
            "sudo apt-get install -y git make golang-go",
            "go install github.com/kgretzky/evilginx/v3@latest",
        ],
        run_command="evilginx",
        project_url="https://github.com/kgretzky/evilginx2",
        tags=["phishing", "mitm", "2fa-bypass", "session-hijack", "evilginx"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="iseeyou",
        title="I-See-You (Location via Social Engineering)",
        description="Finds the exact location of a target via social engineering techniques.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/Viralmaniar/I-See-You.git",
            "cd I-See-You && sudo chmod u+x ISeeYou.sh",
        ],
        run_command="cd I-See-You && sudo bash ISeeYou.sh",
        project_url="https://github.com/Viralmaniar/I-See-You",
        tags=["phishing", "location", "social-engineering", "geolocation"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="saycheese",
        title="SayCheese (Webcam Capture)",
        description="Take webcam shots from target just by sending a malicious link.",
        category="Phishing Attack",
        install_commands=["git clone https://github.com/hangetzzu/saycheese"],
        run_command="cd saycheese && sudo bash saycheese.sh",
        project_url="https://github.com/hangetzzu/saycheese",
        tags=["phishing", "webcam", "social-engineering", "malicious"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="qrjacking",
        title="QR Code Jacking",
        description="QR Code Jacking tool — hijack any website QR login.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/cryptedwolf/ohmyqr.git && sudo apt -y install scrot",
        ],
        run_command="cd ohmyqr && sudo bash ohmyqr.sh",
        project_url="https://github.com/cryptedwolf/ohmyqr",
        tags=["phishing", "qr-code", "social-engineering", "jack"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="blackeye",
        title="BlackEye (38 Website Phishing)",
        description="The ultimate phishing tool with 38 website templates.",
        category="Phishing Attack",
        install_commands=["git clone https://github.com/thelinuxchoice/blackeye"],
        run_command="cd blackeye && sudo bash blackeye.sh",
        project_url="https://github.com/An0nUD4Y/blackeye",
        tags=["phishing", "social-engineering", "templates"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="shellphish",
        title="ShellPhish (18 Social Media)",
        description="Phishing tool for 18 social media platforms.",
        category="Phishing Attack",
        install_commands=["git clone https://github.com/An0nUD4Y/shellphish.git"],
        run_command="cd shellphish && sudo bash shellphish.sh",
        project_url="https://github.com/An0nUD4Y/shellphish",
        tags=["phishing", "social-media", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="thanos",
        title="Thanos (Browser-to-Browser Phishing)",
        description="Browser to Browser Phishing toolkit.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/TridevReddy/Thanos.git",
            "cd Thanos && chmod +x Thanos.sh",
        ],
        run_command="cd Thanos && sudo bash Thanos.sh",
        project_url="https://github.com/TridevReddy/Thanos",
        tags=["phishing", "browser", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="qrljacking",
        title="QRLJacking (Session Hijack via QR)",
        description="Session hijacking attack vector targeting QR code based login systems.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/OWASP/QRLJacking.git",
            "cd QRLJacking && pip3 install --user -r QRLJacker/requirements.txt",
        ],
        run_command="cd QRLJacking/QRLJacker && python3 QrlJacker.py",
        project_url="https://github.com/OWASP/QRLJacking",
        tags=["phishing", "qr-code", "session-hijack", "owasp"],
        safety_tier=SafetyTier.DANGEROUS,
    ),
    HackingToolDef(
        name="maskphish",
        title="Maskphish (URL Masking)",
        description="Hide phishing URL under a normal looking URL (e.g., google.com or facebook.com).",
        category="Phishing Attack",
        install_commands=["git clone https://github.com/jaykali/maskphish.git"],
        run_command="cd maskphish && sudo bash maskphish.sh",
        project_url="https://github.com/jaykali/maskphish",
        tags=["phishing", "url", "masking", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="blackphish",
        title="BlackPhish",
        description="Advanced phishing framework with multiple attack vectors.",
        category="Phishing Attack",
        install_commands=[
            "git clone https://github.com/iinc0gnit0/BlackPhish.git",
            "cd BlackPhish && sudo bash install.sh",
        ],
        run_command="cd BlackPhish && sudo python3 blackphish.py",
        project_url="https://github.com/iinc0gnit0/BlackPhish",
        tags=["phishing", "framework", "social-engineering"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="dnstwist",
        title="dnstwist (Domain Permutation Engine)",
        description="Domain name permutation engine for detecting typosquatting, phishing and brand impersonation.",
        category="Phishing Attack",
        install_commands=["pip3 install --user dnstwist"],
        run_command="dnstwist {target}",
        project_url="https://github.com/elceef/dnstwist",
        tags=["phishing", "dns", "typosquatting", "brand-protection", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
]
