"""SQL Injection tools — detection and exploitation (7 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

SQL_INJECTION_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="sqlmap",
        title="Sqlmap (SQL Injection Automation)",
        description="Automates detection and exploitation of SQL injection flaws and database takeover. Usage: python3 sqlmap.py -u http://example.com --batch",
        category="SQL Injection",
        install_commands=["git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev"],
        run_command="cd sqlmap-dev && python3 sqlmap.py -u {target} --batch",
        project_url="https://github.com/sqlmapproject/sqlmap",
        tags=["sqli", "exploit", "database", "automation", "injection"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="nosqlmap",
        title="NoSqlMap (NoSQL Injection)",
        description="Automated tool for auditing and exploiting NoSQL injection attacks. Requires MongoDB.",
        category="SQL Injection",
        install_commands=[
            "git clone https://github.com/codingo/NoSQLMap.git",
            "cd NoSQLMap && pip install --user .",
        ],
        run_command="python3 -m nosqlmap",
        project_url="https://github.com/codingo/NoSQLMap",
        tags=["nosql", "sqli", "exploit", "mongodb", "injection"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="dsss",
        title="Damn Small SQLi Scanner (DSSS)",
        description="Fully functional SQL injection vulnerability scanner supporting GET and POST parameters. Usage: python3 dsss.py -u [URL]",
        category="SQL Injection",
        install_commands=["git clone https://github.com/stamparm/DSSS.git"],
        run_command="cd DSSS && python3 dsss.py -u {target}",
        project_url="https://github.com/stamparm/DSSS",
        tags=["sqli", "scanner", "web", "injection"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="explo",
        title="Explo (Web Security Tester)",
        description="Describe web security issues in human and machine readable format. Usage: explo testcase.yaml",
        category="SQL Injection",
        install_commands=[
            "git clone https://github.com/dtag-dev-sec/explo.git",
            "cd explo && pip install --user .",
        ],
        run_command="cd explo && explo {target}",
        project_url="https://github.com/dtag-dev-sec/explo",
        tags=["web", "testing", "sqli", "automation"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="blisqy",
        title="Blisqy - Time-based Blind SQL Injection",
        description="Find time-based blind SQL injections on HTTP headers and exploit them.",
        category="SQL Injection",
        install_commands=["git clone https://github.com/JohnTroony/Blisqy.git"],
        run_command="",
        project_url="https://github.com/JohnTroony/Blisqy",
        tags=["sqli", "blind", "time-based", "headers", "exploit"],
        safety_tier=SafetyTier.CAUTION,
        archived=True,
        archived_reason="Upstream provides importable modules and hard-coded examples, but no target-safe CLI entrypoint.",
    ),
    HackingToolDef(
        name="leviathan",
        title="Leviathan - Mass Audit Toolkit",
        description="Mass audit toolkit with service discovery, brute force, SQL injection detection, and custom exploits.",
        category="SQL Injection",
        install_commands=[
            "git clone https://github.com/leviathan-framework/leviathan.git",
            "cd leviathan && pip install --user -r requirements.txt",
        ],
        run_command="cd leviathan && python leviathan.py",
        project_url="https://github.com/leviathan-framework/leviathan",
        tags=["sqli", "audit", "bruteforce", "discovery", "framework"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="sqlscan",
        title="SQLScan (Quick SQL Scanner)",
        description="Quick web scanner to find SQL injection points using PHP.",
        category="SQL Injection",
        install_commands=[
            "sudo apt install php php-bz2 php-curl php-mbstring curl",
            "sudo curl https://raw.githubusercontent.com/Cvar1984/sqlscan/dev/build/main.phar --output /usr/local/bin/sqlscan",
            "chmod +x /usr/local/bin/sqlscan",
        ],
        run_command="sudo sqlscan {target}",
        project_url="https://github.com/Cvar1984/sqlscan",
        tags=["sqli", "scanner", "fast", "web"],
        safety_tier=SafetyTier.SAFE,
    ),
]
