"""Web Attack tools — scanning, fuzzing, discovery, proxies (21 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

WEB_ATTACK_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="web2attack",
        title="Web2Attack",
        description="Web hacking framework with tools and exploits by Python.",
        category="Web Attack",
        install_commands=["git clone https://github.com/santatic/web2attack.git"],
        run_command="cd web2attack && sudo python3 w2aconsole",
        project_url="https://github.com/santatic/web2attack",
        tags=["web", "framework", "exploit"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="skipfish",
        title="Skipfish",
        description="Fully automated, active web application security reconnaissance tool. Usage: skipfish -o [FolderName] target",
        category="Web Attack",
        install_commands=["sudo apt-get install -y skipfish"],
        run_command="sudo skipfish -o skipfish_out {target}",
        tags=["web", "scanner", "automated"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="sublist3r",
        title="Sublist3r (Subdomain Finder)",
        description="Enumerate subdomains of websites using OSINT. Usage: python3 sublist3r.py -d example.com",
        category="Web Attack",
        install_commands=[
            "sudo pip3 install requests argparse dnspython",
            "git clone https://github.com/aboul3la/Sublist3r.git",
            "cd Sublist3r && sudo pip3 install -r requirements.txt",
        ],
        run_command="cd Sublist3r && python3 sublist3r.py -d {target}",
        project_url="https://github.com/aboul3la/Sublist3r",
        tags=["subdomain", "enum", "osint", "dns"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="checkurl",
        title="CheckURL (IDN Homograph Detector)",
        description="Detect evil URLs that use IDN Homograph attacks. Usage: python3 checkURL.py --url google.com",
        category="Web Attack",
        install_commands=["git clone https://github.com/UndeadSec/checkURL.git"],
        run_command="cd checkURL && python3 checkURL.py --url {target}",
        project_url="https://github.com/UndeadSec/checkURL",
        tags=["web", "phishing", "url", "homograph"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="blazy",
        title="Blazy (Login Page Bruteforcer)",
        description="Modern login page bruteforcer. Also detects ClickJacking vulnerabilities.",
        category="Web Attack",
        install_commands=["git clone https://github.com/UltimateHackers/Blazy.git"],
        run_command="cd Blazy && python3 blazy.py -h",
        project_url="https://github.com/UltimateHackers/Blazy",
        tags=["web", "bruteforce", "login", "clickjacking"],
        safety_tier=SafetyTier.SAFE,
        archived=True,
    ),
    HackingToolDef(
        name="takeover",
        title="Sub-Domain TakeOver Checker",
        description="Check for subdomain takeover vulnerabilities (GitHub, AWS/S3, etc.). Usage: python3 takeover.py -d domain.com -v",
        category="Web Attack",
        install_commands=[
            "git clone https://github.com/edoardottt/takeover.git",
            "cd takeover && pip install --user .",
        ],
        run_command="cd takeover && python3 takeover.py -d {target}",
        project_url="https://github.com/edoardottt/takeover",
        tags=["subdomain", "takeover", "vuln", "dns"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="dirb",
        title="Dirb (Web Content Scanner)",
        description="Dictionary-based web content scanner for discovering hidden web objects.",
        category="Web Attack",
        install_commands=[
            "git clone https://gitlab.com/kalilinux/packages/dirb.git",
            "cd dirb && sudo bash configure && make",
        ],
        run_command="sudo dirb {target}",
        project_url="https://gitlab.com/kalilinux/packages/dirb",
        tags=["web", "discovery", "content", "bruteforce"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="nuclei",
        title="Nuclei (Vulnerability Scanner)",
        description="Fast, template-based vulnerability scanner. Usage: nuclei -u https://example.com",
        category="Web Attack",
        install_commands=[
            "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
            "nuclei -update-templates",
        ],
        run_command="nuclei -u {target}",
        project_url="https://github.com/projectdiscovery/nuclei",
        tags=["web", "scanner", "vuln", "template", "fast"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="ffuf",
        title="ffuf (Web Fuzzer)",
        description="Fast web fuzzer — content discovery, parameter fuzzing, vhost discovery. Usage: ffuf -w wordlist.txt -u https://example.com/FUZZ",
        category="Web Attack",
        install_commands=["go install -v github.com/ffuf/ffuf/v2@latest"],
        run_command="ffuf -u {target}",
        project_url="https://github.com/ffuf/ffuf",
        tags=["web", "fuzzing", "discovery", "fast"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="feroxbuster",
        title="Feroxbuster (Directory Brute Force)",
        description="Fast, recursive content discovery tool written in Rust. Usage: feroxbuster -u https://example.com",
        category="Web Attack",
        install_commands=[
            "curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | sudo bash -s /usr/local/bin",
        ],
        run_command="feroxbuster -u {target}",
        project_url="https://github.com/epi052/feroxbuster",
        tags=["web", "discovery", "content", "fast", "recursive"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="nikto",
        title="Nikto (Web Server Scanner)",
        description="Scan web servers for dangerous files, outdated software, misconfigurations. Usage: nikto -h https://example.com",
        category="Web Attack",
        install_commands=["sudo apt-get install -y nikto"],
        run_command="nikto -h {target}",
        project_url="https://github.com/sullo/nikto",
        tags=["web", "scanner", "server", "vuln", "misconfig"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="wafw00f",
        title="wafw00f (WAF Detector)",
        description="Fingerprint and identify Web Application Firewalls (WAF). Usage: wafw00f https://example.com",
        category="Web Attack",
        install_commands=[
            "git clone https://github.com/EnableSecurity/wafw00f.git",
            "cd wafw00f && pip install --user .",
        ],
        run_command="wafw00f {target}",
        project_url="https://github.com/EnableSecurity/wafw00f",
        tags=["web", "waf", "fingerprint", "recon"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="katana",
        title="Katana (Web Crawler)",
        description="Next-generation crawling and spidering framework from ProjectDiscovery. Usage: katana -u https://example.com",
        category="Web Attack",
        install_commands=["go install -v github.com/projectdiscovery/katana/cmd/katana@latest"],
        run_command="katana -u {target}",
        project_url="https://github.com/projectdiscovery/katana",
        tags=["web", "crawler", "spider", "discovery"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="gobuster",
        title="Gobuster (Dir/DNS/Vhost Brute Force)",
        description="Directory/file, DNS, and vhost brute-forcing tool written in Go.",
        category="Web Attack",
        install_commands=["go install github.com/OJ/gobuster/v3@latest"],
        run_command="gobuster dir -u {target}",
        project_url="https://github.com/OJ/gobuster",
        tags=["web", "discovery", "dns", "vhost", "bruteforce"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="dirsearch",
        title="Dirsearch (Web Path Discovery)",
        description="Web path brute-forcing tool for discovering directories and files on web servers.",
        category="Web Attack",
        install_commands=["pip install --user dirsearch"],
        run_command="dirsearch -u {target}",
        project_url="https://github.com/maurosoria/dirsearch",
        tags=["web", "discovery", "content", "bruteforce"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="owasp-zap",
        title="OWASP ZAP (Web App Scanner)",
        description="Full-featured web application security scanner — proxy, spider, fuzzer, scanner.",
        category="Web Attack",
        install_commands=["sudo apt-get install -y zaproxy"],
        run_command="zaproxy -cmd -quickurl {target}",
        project_url="https://github.com/zaproxy/zaproxy",
        tags=["web", "scanner", "proxy", "fuzzer", "full-featured"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="testssl",
        title="testssl.sh (TLS/SSL Checker)",
        description="Check TLS/SSL ciphers, protocols, and cryptographic flaws on any port.",
        category="Web Attack",
        install_commands=["git clone https://github.com/drwetter/testssl.sh.git"],
        run_command="cd testssl.sh && ./testssl.sh {target}",
        project_url="https://github.com/drwetter/testssl.sh",
        tags=["web", "ssl", "tls", "crypto", "misconfig"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="arjun",
        title="Arjun (HTTP Parameter Discovery)",
        description="HTTP parameter discovery suite that finds hidden GET/POST parameters.",
        category="Web Attack",
        install_commands=["pip install --user arjun"],
        run_command="arjun -u {target}",
        project_url="https://github.com/s0md3v/Arjun",
        tags=["web", "parameter", "discovery", "fuzzing"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="caido",
        title="Caido (Web Security Auditing)",
        description="Lightweight, modern web security auditing toolkit — Burp Suite alternative in Rust.",
        category="Web Attack",
        install_commands=[
            "curl -sSL https://caido.download/releases/latest/caido-cli-linux-x86_64.tar.gz | sudo tar xz -C /usr/local/bin",
        ],
        run_command="caido --help",
        project_url="https://github.com/caido/caido",
        tags=["web", "proxy", "audit", "intercept"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="mitmproxy",
        title="mitmproxy (Intercepting Proxy)",
        description="Interactive TLS-capable intercepting HTTP proxy for pentesters and developers.",
        category="Web Attack",
        install_commands=["pip install --user mitmproxy"],
        run_command="mitmproxy --version",
        project_url="https://github.com/mitmproxy/mitmproxy",
        tags=["web", "proxy", "tls", "intercept", "mitm"],
        safety_tier=SafetyTier.CAUTION,
    ),
]
