"""Wireless Attack tools — WiFi, Bluetooth, rogue AP (13 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

WIRELESS_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="wifipumpkin",
        title="WiFi-Pumpkin (Rogue AP Framework)",
        description="Rogue AP framework to easily create fake networks while forwarding legitimate traffic.",
        category="Wireless Attack",
        install_commands=[
            "sudo apt install -y libssl-dev libffi-dev build-essential python3-pyqt5",
            "git clone https://github.com/P0cL4bs/wifipumpkin3.git",
            "chmod -R 755 wifipumpkin3",
            "cd wifipumpkin3 && pip install --user .",
        ],
        run_command="sudo wifipumpkin3",
        project_url="https://github.com/P0cL4bs/wifipumpkin3",
        tags=["wireless", "wifi", "rogue-ap", "mitm", "framework"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="pixiewps",
        title="pixiewps (WPS PIN Bruteforce)",
        description="Bruteforce offline the WPS PIN exploiting low entropy in some Access Points (Pixie Dust attack).",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/wiire/pixiewps.git && apt-get -y install build-essential",
            "cd pixiewps && make && sudo make install",
        ],
        run_command="pixiewps --help",
        project_url="https://github.com/wiire/pixiewps",
        tags=["wireless", "wifi", "wps", "bruteforce", "pixie-dust"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_wifi=True,
    ),
    HackingToolDef(
        name="bluepot",
        title="Bluetooth Honeypot (BluePot)",
        description="Bluetooth honeypot GUI framework. Requires at least 1 Bluetooth receiver.",
        category="Wireless Attack",
        install_commands=[
            "sudo wget https://raw.githubusercontent.com/andrewmichaelsmith/bluepot/master/bin/bluepot-0.2.tar.gz",
            "sudo tar xfz bluepot-0.2.tar.gz && sudo rm bluepot-0.2.tar.gz",
        ],
        run_command="cd bluepot && sudo java -jar bluepot.jar",
        project_url="https://github.com/andrewmichaelsmith/bluepot",
        tags=["wireless", "bluetooth", "honeypot", "java"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="fluxion",
        title="Fluxion (WPA/WPA2 Security Audit)",
        description="WPA/WPA2 security audit using social engineering — remake of linset with enhanced functionality.",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/FluxionNetwork/fluxion.git",
            "cd fluxion && chmod +x fluxion.sh",
        ],
        run_command="cd fluxion && sudo bash fluxion.sh -i",
        project_url="https://github.com/FluxionNetwork/fluxion",
        tags=["wireless", "wifi", "wpa", "social-engineering", "audit"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="wifiphisher",
        title="Wifiphisher (Rogue AP Framework)",
        description="Rogue Access Point framework for red team Wi-Fi security testing with targeted association attacks.",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/wifiphisher/wifiphisher.git",
            "cd wifiphisher && pip install --user .",
        ],
        run_command="cd wifiphisher && sudo wifiphisher",
        project_url="https://github.com/wifiphisher/wifiphisher",
        tags=["wireless", "wifi", "rogue-ap", "red-team", "mitm"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="wifite",
        title="Wifite (Automated Wireless Auditor)",
        description="Automated wireless attack tool for WEP/WPA/WPA2 auditing.",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/derv82/wifite2.git",
            "cd wifite2 && pip install --user .",
        ],
        run_command="sudo wifite",
        project_url="https://github.com/derv82/wifite2",
        tags=["wireless", "wifi", "automated", "wpa", "wep", "audit"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="eviltwin",
        title="EvilTwin (Fake AP Attack)",
        description="Perform Evil Twin Attack by getting credentials using a Fake page and Fake Access Point.",
        category="Wireless Attack",
        install_commands=["git clone https://github.com/Z4nzu/fakeap.git"],
        run_command="cd fakeap && sudo bash fakeap.sh",
        project_url="https://github.com/Z4nzu/fakeap",
        tags=["wireless", "wifi", "evil-twin", "rogue-ap", "credentials"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="fastssh",
        title="Fastssh (SSH Brute Force)",
        description="Multi-threaded scan and brute force attack against SSH protocol using common credentials.",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/Z4nzu/fastssh.git && cd fastssh && chmod +x fastssh.sh",
            "sudo apt-get install -y sshpass netcat",
        ],
        run_command="cd fastssh && sudo bash fastssh.sh --scan",
        project_url="https://github.com/Z4nzu/fastssh",
        tags=["wireless", "ssh", "bruteforce", "network", "scan"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux"],
        requires_root=True,
    ),
    HackingToolDef(
        name="howmanypeople",
        title="Howmanypeople (WiFi Device Counter)",
        description="Count the number of people around you by monitoring WiFi signals. WiFi adapter required.",
        category="Wireless Attack",
        install_commands=[
            "sudo apt-get install -y tshark",
            "sudo python3 -m pip install howmanypeoplearearound",
        ],
        run_command="howmanypeoplearearound",
        tags=["wireless", "wifi", "monitor", "recon"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="airgeddon",
        title="Airgeddon (Wireless Attack Suite)",
        description="Multi-use bash script for auditing wireless networks — WPA/WPA2, WEP, WPS, PMKID, evil twin, handshake capture.",
        category="Wireless Attack",
        install_commands=["git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git"],
        run_command="cd airgeddon && sudo bash airgeddon.sh",
        project_url="https://github.com/v1s1t0r1sh3r3/airgeddon",
        tags=["wireless", "wifi", "wpa", "wep", "wps", "pmkid", "evil-twin", "audit"],
        safety_tier=SafetyTier.DANGEROUS,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
    HackingToolDef(
        name="hcxdumptool",
        title="hcxdumptool (PMKID Capture)",
        description="Capture packets and PMKID hashes from WLAN devices. Usage: hcxdumptool -i <iface> -o capture.pcapng",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/ZerBea/hcxdumptool.git",
            "cd hcxdumptool && make && sudo make install",
        ],
        run_command="hcxdumptool --help",
        project_url="https://github.com/ZerBea/hcxdumptool",
        tags=["wireless", "wifi", "pmkid", "capture", "handshake"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux"],
        requires_wifi=True,
    ),
    HackingToolDef(
        name="hcxtools",
        title="hcxtools (PMKID/Hash Conversion)",
        description="Convert captured WLAN packets to hashcat/John the Ripper-compatible format. Usage: hcxpcapngtool -o hashes.txt capture.pcapng",
        category="Wireless Attack",
        install_commands=[
            "git clone https://github.com/ZerBea/hcxtools.git",
            "cd hcxtools && make && sudo make install",
        ],
        run_command="hcxpcapngtool --help",
        project_url="https://github.com/ZerBea/hcxtools",
        tags=["wireless", "wifi", "hashcat", "conversion", "handshake"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="bettercap",
        title="Bettercap (Network/WiFi/BLE MITM)",
        description="Swiss army knife for WiFi, BLE, HID, and Ethernet network recon and MITM attacks.",
        category="Wireless Attack",
        install_commands=["sudo apt-get install -y bettercap"],
        run_command="sudo bettercap --help",
        project_url="https://github.com/bettercap/bettercap",
        tags=["wireless", "wifi", "ble", "mitm", "network", "recon"],
        safety_tier=SafetyTier.CAUTION,
        supported_os=["linux"],
        requires_root=True,
        requires_wifi=True,
    ),
]
