"""Wordlist Generator tools — password profiling, generation, cracking (7 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

WORDLIST_GENERATOR_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="cupp",
        title="Cupp (Common User Passwords Profiler)",
        description="Generates personalized wordlists based on target information (name, dob, pet, etc.).",
        category="Wordlist Generator",
        install_commands=["git clone https://github.com/Mebus/cupp.git"],
        run_command="cd cupp && python3 cupp.py -i",
        project_url="https://github.com/Mebus/cupp",
        tags=["wordlist", "password", "profiler", "social-engineering"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="wlcreator",
        title="WordlistCreator (wlcreator)",
        description="C program that generates all password possibilities with configurable length, lowercase, capitals, numbers, and special chars.",
        category="Wordlist Generator",
        install_commands=["git clone https://github.com/Z4nzu/wlcreator.git"],
        run_command="cd wlcreator && sudo gcc -o wlcreator wlcreator.c && ./wlcreator 5",
        project_url="https://github.com/Z4nzu/wlcreator",
        tags=["wordlist", "password", "generator", "bruteforce"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="goblin-wordgenerator",
        title="Goblin WordGenerator",
        description="Pattern-based wordlist generator for customized password lists.",
        category="Wordlist Generator",
        install_commands=["git clone https://github.com/UndeadSec/GoblinWordGenerator.git"],
        run_command="cd GoblinWordGenerator && python3 goblin.py",
        project_url="https://github.com/UndeadSec/GoblinWordGenerator",
        tags=["wordlist", "password", "generator", "pattern"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="showme",
        title="ShowMe (1.4 Billion Clear Text Passwords)",
        description="OSINT tool to search 1.4 Billion clear text credentials from the BreachCompilation leak.",
        category="Wordlist Generator",
        install_commands=[
            "git clone https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got.git",
            "cd SMWYG-Show-Me-What-You-Got && pip3 install -r requirements.txt",
        ],
        run_command="cd SMWYG-Show-Me-What-You-Got && python3 SMWYG.py",
        project_url="https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got",
        tags=["wordlist", "password", "breach", "osint", "credentials"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="hashcat",
        title="Hashcat (Password Cracker)",
        description="World's fastest GPU/CPU password recovery tool — supports 300+ hash types. Usage: hashcat -m 0 -a 0 hashes.txt wordlist.txt",
        category="Wordlist Generator",
        install_commands=["sudo apt-get install -y hashcat"],
        run_command="hashcat",
        project_url="https://github.com/hashcat/hashcat",
        tags=["password", "cracker", "hash", "gpu", "recovery"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="john",
        title="John the Ripper (Password Cracker)",
        description="Open-source password security auditing and recovery tool. Usage: john --wordlist=wordlist.txt hashfile",
        category="Wordlist Generator",
        install_commands=["sudo apt-get install -y john"],
        run_command="john",
        project_url="https://github.com/openwall/john",
        tags=["password", "cracker", "hash", "audit", "recovery"],
        safety_tier=SafetyTier.SAFE,
        supported_os=["linux"],
    ),
    HackingToolDef(
        name="haiti",
        title="haiti (Hash Type Identifier)",
        description="Identify hash types — supports 300+ algorithms. Usage: haiti <hash>",
        category="Wordlist Generator",
        install_commands=["gem install haiti-hash"],
        run_command="haiti {target}",
        project_url="https://github.com/noraj/haiti",
        tags=["hash", "identifier", "forensics", "crypto"],
        safety_tier=SafetyTier.SAFE,
    ),
]
