"""XSS Attack tools — detection, scanning, exploitation (10 tools)."""

from hacking_mcp.models import HackingToolDef, SafetyTier

XSS_ATTACK_TOOLS: list[HackingToolDef] = [
    HackingToolDef(
        name="dalfox",
        title="DalFox (XSS Finder)",
        description="XSS scanning and parameter analysis tool. Usage: dalfox url https://example.com",
        category="XSS Attack",
        install_commands=[
            "sudo apt-get install -y golang",
            "go install github.com/hahwul/dalfox/v2@latest",
        ],
        run_command="dalfox url {target}",
        project_url="https://github.com/hahwul/dalfox",
        tags=["xss", "scanner", "parameter", "web"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xssfinder",
        title="Extended XSS Searcher and Finder",
        description="Extended XSS Searcher and Finder. Multi-threaded XSS detection on lists of URLs.",
        category="XSS Attack",
        install_commands=[
            "git clone https://github.com/Damian89/extended-xss-search.git",
        ],
        run_command="cd extended-xss-search && python3 app.py",
        project_url="https://github.com/Damian89/extended-xss-search",
        tags=["xss", "scanner", "finder", "extended"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xss-payload-generator",
        title="XSS Payload Generator",
        description="XSS Payload Generator, XSS Scanner, and XSS Dork Finder.",
        category="XSS Attack",
        install_commands=[
            "git clone https://github.com/capture0x/XSS-LOADER.git",
            "cd XSS-LOADER && sudo pip3 install -r requirements.txt",
        ],
        run_command="cd XSS-LOADER && sudo python3 payloader.py",
        project_url="https://github.com/capture0x/XSS-LOADER",
        tags=["xss", "payload", "generator", "scanner"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="xss-freak",
        title="XSS-Freak",
        description="XSS scanner fully written in Python 3 from scratch.",
        category="XSS Attack",
        install_commands=[
            "git clone https://github.com/PR0PH3CY33/XSS-Freak.git",
            "cd XSS-Freak && sudo pip3 install -r requirements.txt",
        ],
        run_command="cd XSS-Freak && sudo python3 XSS-Freak.py",
        project_url="https://github.com/PR0PH3CY33/XSS-Freak",
        tags=["xss", "scanner", "python"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xspear",
        title="XSpear (XSS Scanner - Ruby)",
        description="XSS scanner built on Ruby Gems. Usage: XSpear -u https://example.com",
        category="XSS Attack",
        install_commands=["gem install XSpear"],
        run_command="XSpear -u {target}",
        project_url="https://github.com/hahwul/XSpear",
        tags=["xss", "scanner", "ruby"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xsscon",
        title="XSSCon",
        description="XSS vulnerability scanner with multiple detection modes.",
        category="XSS Attack",
        install_commands=[
            "git clone https://github.com/menkrep1337/XSSCon.git",
            "sudo chmod 755 -R XSSCon",
        ],
        run_command="cd XSSCon && python3 xsscon.py -u {target}",
        project_url="https://github.com/menkrep1337/XSSCon",
        tags=["xss", "scanner", "web"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xanxss",
        title="XanXSS (Reflected XSS)",
        description="Reflected XSS searching tool that creates payloads from templates.",
        category="XSS Attack",
        install_commands=["git clone https://github.com/Ekultek/XanXSS.git"],
        run_command="cd XanXSS && python3 xanxss.py -u {target}",
        project_url="https://github.com/Ekultek/XanXSS",
        tags=["xss", "reflected", "scanner", "payload"],
        safety_tier=SafetyTier.SAFE,
    ),
    HackingToolDef(
        name="xsstrike",
        title="XSStrike (Advanced XSS Detection)",
        description="Advanced XSS detection suite with intelligent payload generation and WAF detection.",
        category="XSS Attack",
        install_commands=[
            "sudo rm -rf XSStrike",
            "git clone https://github.com/UltimateHackers/XSStrike.git && cd XSStrike && pip install -r requirements.txt",
        ],
        run_command="cd XSStrike && python3 xsstrike.py -u {target}",
        project_url="https://github.com/UltimateHackers/XSStrike",
        tags=["xss", "advanced", "scanner", "waf", "payload"],
        safety_tier=SafetyTier.CAUTION,
    ),
    HackingToolDef(
        name="rvuln",
        title="RVuln (Rust Vulnerability Scanner)",
        description="Multi-threaded and automated Web Vulnerability Scanner written in Rust.",
        category="XSS Attack",
        install_commands=[
            "git clone https://github.com/iinc0gnit0/RVuln.git",
            "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
            "cd RVuln && cargo build --release",
        ],
        run_command="RVuln {target}",
        project_url="https://github.com/iinc0gnit0/RVuln",
        tags=["web", "scanner", "vuln", "rust", "multithreaded"],
        safety_tier=SafetyTier.SAFE,
    ),
]
