"""Registry for split-out dedicated per-tool adapters."""

from collections.abc import Callable

from hacking_mcp.mcp_tools.adapter_types import AdapterParameterSpec
from hacking_mcp.mcp_tools.adapters import (
    androguard,
    amass,
    arjun,
    apk2gold,
    binwalk,
    blisqy,
    bloodhound,
    certipy,
    chisel,
    commix,
    dalfox,
    dirsearch,
    dsss,
    evil_winrm,
    explo,
    feroxbuster,
    ffuf,
    frida,
    ghidra,
    gitleaks,
    gobuster,
    haiti,
    hashcat,
    havoc,
    httpx,
    impacket,
    jadx,
    john,
    katana,
    masscan,
    mobsf,
    kerbrute,
    leviathan,
    ligolo_ng,
    netexec,
    nikto,
    nmap,
    nosqlmap,
    nuclei,
    objection,
    owasp_zap,
    pacu,
    peass_ng,
    pspy,
    prowler,
    pwncat_cs,
    radare2,
    responder,
    routersploit,
    rustscan,
    scoutsuite,
    sherlock,
    sliver,
    sqlscan,
    sqlmap,
    stegcracker,
    steghide,
    subfinder,
    testssl,
    theharvester,
    trufflehog,
    trivy,
    volatility3,
    wafw00f,
    websploit,
    whatweb,
    xanxss,
    xspear,
    xsstrike,
    xsscon,
)


ParameterProvider = Callable[[], list[AdapterParameterSpec]]
OptionsBuilder = Callable[[dict], list[str]]


PARAMETER_PROVIDERS: dict[str, ParameterProvider] = {
    "androguard": androguard.parameters,
    "amass": amass.parameters,
    "arjun": arjun.parameters,
    "apk2gold": apk2gold.parameters,
    "binwalk": binwalk.parameters,
    "blisqy": blisqy.parameters,
    "bloodhound": bloodhound.parameters,
    "certipy": certipy.parameters,
    "chisel": chisel.parameters,
    "commix": commix.parameters,
    "dalfox": dalfox.parameters,
    "dirsearch": dirsearch.parameters,
    "dsss": dsss.parameters,
    "evil-winrm": evil_winrm.parameters,
    "explo": explo.parameters,
    "feroxbuster": feroxbuster.parameters,
    "ffuf": ffuf.parameters,
    "frida": frida.parameters,
    "ghidra": ghidra.parameters,
    "gitleaks": gitleaks.parameters,
    "gobuster": gobuster.parameters,
    "haiti": haiti.parameters,
    "hashcat": hashcat.parameters,
    "havoc": havoc.parameters,
    "httpx": httpx.parameters,
    "impacket": impacket.parameters,
    "jadx": jadx.parameters,
    "john": john.parameters,
    "katana": katana.parameters,
    "masscan": masscan.parameters,
    "mobsf": mobsf.parameters,
    "kerbrute": kerbrute.parameters,
    "leviathan": leviathan.parameters,
    "ligolo-ng": ligolo_ng.parameters,
    "netexec": netexec.parameters,
    "nikto": nikto.parameters,
    "nmap": nmap.parameters,
    "nosqlmap": nosqlmap.parameters,
    "nuclei": nuclei.parameters,
    "objection": objection.parameters,
    "owasp-zap": owasp_zap.parameters,
    "pacu": pacu.parameters,
    "peass-ng": peass_ng.parameters,
    "pspy": pspy.parameters,
    "prowler": prowler.parameters,
    "pwncat-cs": pwncat_cs.parameters,
    "radare2": radare2.parameters,
    "responder": responder.parameters,
    "routersploit": routersploit.parameters,
    "rustscan": rustscan.parameters,
    "scoutsuite": scoutsuite.parameters,
    "sherlock": sherlock.parameters,
    "sliver": sliver.parameters,
    "sqlscan": sqlscan.parameters,
    "sqlmap": sqlmap.parameters,
    "stegcracker": stegcracker.parameters,
    "steghide": steghide.parameters,
    "subfinder": subfinder.parameters,
    "testssl": testssl.parameters,
    "theHarvester": theharvester.parameters,
    "trufflehog": trufflehog.parameters,
    "trivy": trivy.parameters,
    "volatility3": volatility3.parameters,
    "wafw00f": wafw00f.parameters,
    "websploit": websploit.parameters,
    "whatweb": whatweb.parameters,
    "xanxss": xanxss.parameters,
    "xspear": xspear.parameters,
    "xsstrike": xsstrike.parameters,
    "xsscon": xsscon.parameters,
}

OPTIONS_BUILDERS: dict[str, OptionsBuilder] = {
    "androguard": androguard.build_options,
    "amass": amass.build_options,
    "arjun": arjun.build_options,
    "apk2gold": apk2gold.build_options,
    "binwalk": binwalk.build_options,
    "blisqy": blisqy.build_options,
    "bloodhound": bloodhound.build_options,
    "certipy": certipy.build_options,
    "chisel": chisel.build_options,
    "commix": commix.build_options,
    "dalfox": dalfox.build_options,
    "dirsearch": dirsearch.build_options,
    "dsss": dsss.build_options,
    "evil-winrm": evil_winrm.build_options,
    "explo": explo.build_options,
    "feroxbuster": feroxbuster.build_options,
    "ffuf": ffuf.build_options,
    "frida": frida.build_options,
    "ghidra": ghidra.build_options,
    "gitleaks": gitleaks.build_options,
    "gobuster": gobuster.build_options,
    "haiti": haiti.build_options,
    "hashcat": hashcat.build_options,
    "havoc": havoc.build_options,
    "httpx": httpx.build_options,
    "impacket": impacket.build_options,
    "jadx": jadx.build_options,
    "john": john.build_options,
    "katana": katana.build_options,
    "masscan": masscan.build_options,
    "mobsf": mobsf.build_options,
    "kerbrute": kerbrute.build_options,
    "leviathan": leviathan.build_options,
    "ligolo-ng": ligolo_ng.build_options,
    "netexec": netexec.build_options,
    "nikto": nikto.build_options,
    "nmap": nmap.build_options,
    "nosqlmap": nosqlmap.build_options,
    "nuclei": nuclei.build_options,
    "objection": objection.build_options,
    "owasp-zap": owasp_zap.build_options,
    "pacu": pacu.build_options,
    "peass-ng": peass_ng.build_options,
    "pspy": pspy.build_options,
    "prowler": prowler.build_options,
    "pwncat-cs": pwncat_cs.build_options,
    "radare2": radare2.build_options,
    "responder": responder.build_options,
    "routersploit": routersploit.build_options,
    "rustscan": rustscan.build_options,
    "scoutsuite": scoutsuite.build_options,
    "sherlock": sherlock.build_options,
    "sliver": sliver.build_options,
    "sqlscan": sqlscan.build_options,
    "sqlmap": sqlmap.build_options,
    "stegcracker": stegcracker.build_options,
    "steghide": steghide.build_options,
    "subfinder": subfinder.build_options,
    "testssl": testssl.build_options,
    "theHarvester": theharvester.build_options,
    "trufflehog": trufflehog.build_options,
    "trivy": trivy.build_options,
    "volatility3": volatility3.build_options,
    "wafw00f": wafw00f.build_options,
    "websploit": websploit.build_options,
    "whatweb": whatweb.build_options,
    "xanxss": xanxss.build_options,
    "xspear": xspear.build_options,
    "xsstrike": xsstrike.build_options,
    "xsscon": xsscon.build_options,
}


def has_split_adapter(tool_name: str) -> bool:
    return tool_name in PARAMETER_PROVIDERS and tool_name in OPTIONS_BUILDERS


def split_adapter_parameters(tool_name: str) -> list[AdapterParameterSpec] | None:
    provider = PARAMETER_PROVIDERS.get(tool_name)
    if provider is None:
        return None
    return provider()


def split_adapter_options(tool_name: str, kwargs: dict) -> list[str] | None:
    builder = OPTIONS_BUILDERS.get(tool_name)
    if builder is None:
        return None
    return builder(kwargs)
